# Generated by Django 5.1.2 on 2024-11-06 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0001_initial'),
        ('Teachers', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectdb',
            name='batch',
            field=models.ForeignKey(default='00-00', on_delete=django.db.models.deletion.CASCADE, to='Teachers.batch'),
        ),
        migrations.AddField(
            model_name='subjectdb',
            name='branch',
            field=models.ForeignKey(default='SIES', on_delete=django.db.models.deletion.CASCADE, to='Teachers.branch'),
        ),
        migrations.AddField(
            model_name='subjectdb',
            name='content_type',
            field=models.ForeignKey(default='Subject', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='subjectdb',
            name='email',
            field=models.ForeignKey(default='Email', on_delete=django.db.models.deletion.CASCADE, to='Admin.adminusers'),
        ),
    ]
