# Generated by Django 5.1.2 on 2024-11-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectdb',
            name='COs',
        ),
        migrations.RemoveField(
            model_name='subjectdb',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='subjectdb',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='subjectdb',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='subjectdb',
            name='email',
        ),
        migrations.RemoveField(
            model_name='subjectdb',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='subjectdb',
            name='srno',
        ),
        migrations.AddField(
            model_name='subjectdb',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
