# Generated by Django 5.1.2 on 2024-11-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_remove_subjectdb_cos_remove_subjectdb_batch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminusers',
            name='email',
        ),
        migrations.RemoveField(
            model_name='adminusers',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='adminusers',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='adminusers',
            name='password',
        ),
        migrations.RemoveField(
            model_name='adminusers',
            name='sem',
        ),
        migrations.RemoveField(
            model_name='adminusers',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='adminusers',
            name='username',
        ),
        migrations.RemoveField(
            model_name='adminusers',
            name='usertype',
        ),
        migrations.AddField(
            model_name='adminusers',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
