# Generated by Django 5.1.2 on 2024-11-06 20:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_remove_adminusers_email_remove_adminusers_fname_and_more'),
        ('Teachers', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminusers',
            name='id',
        ),
        migrations.AddField(
            model_name='adminusers',
            name='email',
            field=models.CharField(default='name@gmail/sies.edu.in', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='adminusers',
            name='fname',
            field=models.CharField(default='FirstName', max_length=10),
        ),
        migrations.AddField(
            model_name='adminusers',
            name='lname',
            field=models.CharField(default='LastName', max_length=10),
        ),
        migrations.AddField(
            model_name='adminusers',
            name='password',
            field=models.CharField(default='Password', max_length=15),
        ),
        migrations.AddField(
            model_name='adminusers',
            name='sem',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AddField(
            model_name='adminusers',
            name='slug',
            field=models.SlugField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='adminusers',
            name='username',
            field=models.CharField(default='UserName', max_length=15),
        ),
        migrations.AddField(
            model_name='adminusers',
            name='usertype',
            field=models.CharField(default='TE', max_length=2),
        ),
        migrations.AddField(
            model_name='subjectdb',
            name='COs',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='subjectdb',
            name='batch',
            field=models.ForeignKey(default='00-00', on_delete=django.db.models.deletion.CASCADE, to='Teachers.batch'),
        ),
        migrations.AddField(
            model_name='subjectdb',
            name='branch',
            field=models.ForeignKey(default='SIES', on_delete=django.db.models.deletion.CASCADE, to='Teachers.branch'),
        ),
        migrations.AddField(
            model_name='subjectdb',
            name='content_type',
            field=models.ForeignKey(default='Subject', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='subjectdb',
            name='email',
            field=models.ForeignKey(default='Email', on_delete=django.db.models.deletion.CASCADE, to='Admin.adminusers'),
        ),
        migrations.AddField(
            model_name='subjectdb',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
