# Generated by Django 5.1.2 on 2024-11-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='srno',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Username',
            field=models.CharField(max_length=30),
        ),
    ]
