# Generated by Django 5.1.2 on 2024-10-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USERS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='python', max_length=100)),
                ('usertype', models.CharField(default='TE', max_length=2)),
                ('password', models.CharField(default='NULL', max_length=15)),
                ('fname', models.CharField(default='default', max_length=10)),
                ('lname', models.CharField(default='default', max_length=10)),
            ],
        ),
    ]
