# Generated by Django 5.1.2 on 2024-10-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='subject',
            field=models.CharField(default='Subject', max_length=10),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(default='name@gmail/sies.edu.in', max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='fname',
            field=models.CharField(default='FirstName', max_length=10),
        ),
        migrations.AlterField(
            model_name='users',
            name='lname',
            field=models.CharField(default='LastName', max_length=10),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='Password', max_length=15),
        ),
    ]
