# Generated by Django 5.1.2 on 2024-10-24 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_users_subject_alter_users_email_alter_users_fname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='subject',
        ),
    ]
